spring.application.name=ecommercePOC
spring.datasource.url=jdbc:mysql://localhost:3306/Ecommerce_Poc_db
spring.datasource.username=root
spring.datasource.password=Ritik@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true